
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/Provider/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "blocks",
  description: "Generated by create next app",
  icons: "/logo.svg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="tr" className=" " suppressHydrationWarning>
      <body className={inter.className} >
        <ThemeProvider 
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        >
          <main>
            <Navbar />
            <div className="my-20  ">
              {children}
            </div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}